---
action:
- service: light.toggle
  target:
    entity_id: light.ensuite_downlights
alias: Ensuite Downlights
mode: single
trigger:
- entity_id: binary_sensor.ensuite_switch_01
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.ensuite_switch_02
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.ensuite_switch_03
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.ensuite_switch_01
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.ensuite_switch_02
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.ensuite_switch_03
  from: "off"
  platform: state
  to: "on"
