---
actioff:
- service: homeassistant.turn_off
  target:
    entity_id: switch.ensuite_fan
alias: Ensuite Fan On
mode: single
trigger:
- entity_id:
  - light.ensuite_downlights
  platform: state
  to: "off"
