---
automation: !include automations.yaml
# Loads default set of integrations. Do not remove.
default_config:
scene: !include scenes.yaml
script: !include scripts.yaml
tts:
- platform: google_translate
