---
automation: !include automations.yaml
# Loads default set of integrations. Do not remove.
default_config:
http:
  trusted_proxies:
  - 172.24.0.0/16
  use_x_forwarded_for: true
scene: !include scenes.yaml
script: !include scripts.yaml
tts:
- platform: google_translate
