---
title: Moonya
views:
- cards:
  - link_dashboard: true
    title: Energy distribution today
    type: energy-distribution
  - entities:
    - person.andrew_cole
    type: entities
  - cards:
    - entity: climate.bedroom_air_conditioner
      type: thermostat
    - entity: climate.kitchen_air_conditioner
      type: thermostat
    - entity: climate.lounge_air_conditioner
      type: thermostat
    - entity: climate.office_air_conditioner
      type: thermostat
    columns: 1
    square: false
    type: grid
  - entities:
    - light.backyard_downlight_01
    - light.backyard_downlight_02
    - light.backyard_downlight_03
    - light.backyard_downlight_04
    - light.backyard_downlights
    - light.backyard_lights
    - light.bedroom_downlight_01
    - light.bedroom_downlight_02
    - light.bedroom_downlight_03
    - light.bedroom_downlight_04
    - light.bedroom_downlights
    - light.bedroom_lights
    - light.bedroom_tablelight_01
    - light.bedroom_tablelight_02
    - light.bedroom_tablelights
    - light.driveway_downlight_01
    - light.driveway_downlights
    - light.driveway_lights
    - light.ensuite_downlight_01
    - light.ensuite_downlights
    - light.ensuite_lights
    - light.ensuite_nightlight_01
    - light.ensuite_nightlights
    - light.entrance_downlight_01
    - light.entrance_downlights
    - light.entrance_lights
    - light.garage_downlight_01
    - light.garage_downlight_02
    - light.garage_downlights
    - light.kitchen_downlight_01
    - light.kitchen_downlight_02
    - light.kitchen_downlight_03
    - light.kitchen_downlight_04
    - light.kitchen_downlight_05
    - light.kitchen_downlight_06
    - light.kitchen_downlight_07
    - light.kitchen_downlight_08
    - light.kitchen_downlight_09
    - light.kitchen_downlight_10
    - light.kitchen_downlight_11
    - light.kitchen_downlight_12
    - light.kitchen_downlights
    - light.kitchen_downlights_a
    - light.kitchen_downlights_b
    - light.kitchen_lights
    - light.kitchen_nightlight_01
    - light.kitchen_nightlights
    - light.laundry_downlight_01
    - light.laundry_downlights
    - light.laundry_lights
    - light.laundry_nightlights
    - light.lounge_downlight_01
    - light.lounge_downlight_02
    - light.lounge_downlight_03
    - light.lounge_downlight_04
    - light.lounge_downlight_05
    - light.lounge_downlights
    - light.lounge_lights
    - light.lounge_tablelight_01
    - light.lounge_tablelight_02
    - light.lounge_tablelight_03
    - light.lounge_tablelight_04
    - light.lounge_tablelights
    - light.office_downlight_01
    - light.office_downlight_02
    - light.office_downlight_03
    - light.office_downlights
    - light.office_lights
    - light.office_tablelights
    - light.stairwell_downlight_01
    - light.stairwell_downlight_02
    - light.stairwell_downlight_03
    - light.stairwell_downlights
    - light.stairwell_nightlight_01
    - light.stairwell_nightlights
    title: Light
    type: entities
  - cards:
    - entity: media_player.all_speakers
      type: media-control
    - entity: media_player.bedroom_speaker
      type: media-control
    - entity: media_player.garage_speaker
      type: media-control
    - entity: media_player.kitchen_shield
      type: media-control
    - entity: media_player.kitchen_speaker
      type: media-control
    - entity: media_player.lounge_room_tv_2
      type: media-control
    - entity: media_player.lounge_room_tv
      type: media-control
    - entity: media_player.lounge_shield
      type: media-control
    - entity: media_player.lounge_speaker
      type: media-control
    - entity: media_player.office_shield
      type: media-control
    - entity: media_player.office_speaker
      type: media-control
    columns: 1
    square: false
    type: grid
  - entities:
    - sensor.backyard_downlight_01_current
    - sensor.backyard_downlight_01_power
    - sensor.backyard_downlight_02_current
    - sensor.backyard_downlight_02_power
    - sensor.backyard_downlight_03_current
    - sensor.backyard_downlight_03_power
    - sensor.backyard_downlight_04_current
    - sensor.backyard_downlight_04_power
    - sensor.backyard_downlights_power
    - sensor.backyard_humidity
    - sensor.backyard_lights_power
    - sensor.backyard_temperature
    - sensor.bedroom_downlight_01_current
    - sensor.bedroom_downlight_01_power
    - sensor.bedroom_downlight_02_current
    - sensor.bedroom_downlight_02_power
    - sensor.bedroom_downlight_03_current
    - sensor.bedroom_downlight_03_power
    - sensor.bedroom_downlight_04_current
    - sensor.bedroom_downlight_04_power
    - sensor.bedroom_downlights_power
    - sensor.bedroom_humidity
    - sensor.bedroom_temperature
    - sensor.driveway_downlight_01_current
    - sensor.driveway_downlight_01_power
    - sensor.driveway_downlights_power
    - sensor.driveway_lights_power
    - sensor.dryer_current
    - sensor.dryer_mode
    - sensor.dryer_power
    - sensor.dryer_voltage
    - sensor.ensuite_downlight_01_current
    - sensor.ensuite_downlight_01_power
    - sensor.ensuite_downlights_power
    - sensor.ensuite_fan_01_current
    - sensor.ensuite_fan_01_power
    - sensor.ensuite_fan_02_current
    - sensor.ensuite_fan_02_power
    - sensor.ensuite_fans_power
    - sensor.ensuite_lights_power
    - sensor.ensuite_nightlight_01_current
    - sensor.ensuite_nightlight_01_power
    - sensor.ensuite_nightlights_power
    - sensor.entrance_downlight_01_current
    - sensor.entrance_downlight_01_power
    - sensor.entrance_downlights_power
    - sensor.entrance_lights_power
    - sensor.fridge_current
    - sensor.fridge_power
    - sensor.fridge_voltage
    - sensor.garage_downlight_01_current
    - sensor.garage_downlight_01_power
    - sensor.garage_downlight_02_current
    - sensor.garage_downlight_02_power
    - sensor.garage_humidity
    - sensor.garage_temperature
    - sensor.george_moisture_sensor
    - sensor.gracie_moisture_sensor
    - sensor.kitchen_downlights_power
    - sensor.kitchen_humidity
    - sensor.kitchen_power_01_current
    - sensor.kitchen_power_01_power
    - sensor.kitchen_power_02_current
    - sensor.kitchen_power_02_power
    - sensor.kitchen_power_03_current
    - sensor.kitchen_power_03_power
    - sensor.kitchen_power_04_current
    - sensor.kitchen_power_04_power
    - sensor.kitchen_temperature
    - sensor.laundry_downlight_01_current
    - sensor.laundry_downlight_01_power
    - sensor.laundry_downlights_power
    - sensor.laundry_fan_01_current
    - sensor.laundry_fan_01_power
    - sensor.laundry_fans_power
    - sensor.laundry_humidity
    - sensor.laundry_lights_power
    - sensor.laundry_nightlights_power
    - sensor.laundry_temperature
    - sensor.lounge_downlights_power
    - sensor.lounge_power_01_current
    - sensor.lounge_power_01_power
    - sensor.lounge_power_02_current
    - sensor.lounge_power_02_power
    - sensor.climate_on_count
    - sensor.lights_on_count
    - sensor.office_downlights_power
    - sensor.office_lights_power
    - sensor.office_power_01_current
    - sensor.office_power_01_power
    - sensor.office_power_02_current
    - sensor.office_power_02_power
    - sensor.office_power_03_current
    - sensor.office_power_03_power
    - sensor.office_power_04_current
    - sensor.office_power_04_power
    - sensor.office_tablelights_power
    - sensor.server_rack_current
    - sensor.server_rack_energy
    - sensor.server_rack_power
    - sensor.server_rack_total_daily_energy
    - sensor.server_rack_voltage
    - sensor.stairwell_downlight_01_current
    - sensor.stairwell_downlight_01_power
    - sensor.stairwell_downlight_02_current
    - sensor.stairwell_downlight_02_power
    - sensor.stairwell_downlight_03_current
    - sensor.stairwell_downlight_03_power
    - sensor.stairwell_nightlight_01_current
    - sensor.stairwell_nightlight_01_power
    - sensor.washing_machine_current
    - sensor.washing_machine_power
    - sensor.washing_machine_voltage
    - sensor.moo_shelly_01_temperature
    - sensor.moo_shelly_01_voltage
    - sensor.moo_shelly_02_temperature
    - sensor.moo_shelly_02_voltage
    - sensor.moo_shelly_03_temperature
    - sensor.moo_shelly_03_voltage
    - sensor.moo_shelly_04_temperature
    - sensor.moo_shelly_04_voltage
    - sensor.moo_shelly_05_temperature
    - sensor.moo_shelly_05_voltage
    - sensor.moo_shelly_06_temperature
    - sensor.moo_shelly_06_voltage
    - sensor.moo_shelly_07_temperature
    - sensor.moo_shelly_07_voltage
    - sensor.moo_shelly_08_temperature
    - sensor.moo_shelly_08_voltage
    - sensor.moo_shelly_09_temperature
    - sensor.moo_shelly_09_voltage
    - sensor.moo_shelly_10_temperature
    - sensor.moo_shelly_10_voltage
    - sensor.moo_shelly_11_temperature
    - sensor.moo_shelly_11_voltage
    - sensor.moo_shelly_12_temperature
    - sensor.moo_shelly_12_voltage
    - sensor.moo_shelly_13_temperature
    - sensor.moo_shelly_13_voltage
    - sensor.moo_shelly_14_temperature
    - sensor.moo_shelly_14_voltage
    - sensor.moo_shelly_15_temperature
    - sensor.moo_shelly_15_voltage
    - sensor.moo_shelly_17_temperature
    - sensor.moo_shelly_17_voltage
    title: Sensor
    type: entities
  - entities:
    - switch.downstairs_access_point
    - switch.dryer
    - switch.ensuite_fan_01
    - switch.ensuite_fan_02
    - switch.fridge
    - switch.kitchen_google_mini
    - switch.kitchen_power_01
    - switch.kitchen_power_02
    - switch.kitchen_power_03
    - switch.kitchen_power_04
    - switch.lounge_google_mini
    - switch.lounge_power_01
    - switch.lounge_power_02
    - switch.office_google_mini
    - switch.office_power_01
    - switch.office_power_02
    - switch.office_power_03
    - switch.office_power_04
    - switch.server_rack
    - switch.upstairs_access_point
    - switch.virtual_reality_lighthouses
    - switch.washing_machine
    title: Switch
    type: entities
  - entity: weather.forecast_moonya
    show_forecast: false
    type: weather-forecast
  path: default_view
  title: Home
- cards: []
  path: backyard
  title: Backyard
- cards:
  - entities:
    - binary_sensor.bedroom_switch_01
    - binary_sensor.bedroom_switch_02
    - binary_sensor.bedroom_switch_03
    - binary_sensor.bedroom_switch_04
    title: Switches
    type: entities
  path: bedroom
  title: Bedroom
- cards: []
  path: driveway
  title: Driveway
- cards:
  - entities:
    - binary_sensor.ensuite_switch_01
    - binary_sensor.ensuite_switch_02
    - binary_sensor.ensuite_switch_03
    - binary_sensor.ensuite_switch_04
    title: Switches
    type: entities
  path: ensuite
  title: Ensuite
- cards:
  - entities:
    - binary_sensor.entrance_switch_01
    - binary_sensor.entrance_switch_02
    title: Switches
    type: entities
  path: entrance
  title: Entrance
- cards:
  - entities:
    - binary_sensor.garage_motion_01
    - binary_sensor.garage_motion_02
    - binary_sensor.garage_switch_01
    - binary_sensor.garage_switch_02
    title: Switches
    type: entities
  path: garage
  title: Garage
- cards:
  - entities:
    - binary_sensor.laundry_switch_01
    - binary_sensor.laundry_switch_02
    - binary_sensor.lounge_switch_01
    - binary_sensor.lounge_switch_02
    - binary_sensor.office_switch_01
    - binary_sensor.office_switch_02
    - binary_sensor.office_switch_03
    - binary_sensor.office_switch_04
    - binary_sensor.stairwell_switch_01
    - binary_sensor.stairwell_switch_02
    - binary_sensor.stairwell_switch_03
    - binary_sensor.stairwell_switch_04
    title: Switches
    type: entities
  path: kitchen
  title: Kitchen
- cards:
  - entities:
    - binary_sensor.laundry_switch_01
    - binary_sensor.laundry_switch_02
    title: Switches
    type: entities
  - entities:
    - switch.laundry_fan_01
    show_header_toggle: true
    title: Fans
    type: entities
  path: laundry
  title: Laundry
- cards:
  - entities:
    - binary_sensor.lounge_switch_01
    - binary_sensor.lounge_switch_02
    title: Switches
    type: entities
  path: lounge
  title: Lounge Room
- cards:
  - entities:
    - binary_sensor.office_switch_01
    - binary_sensor.office_switch_02
    - binary_sensor.office_switch_03
    - binary_sensor.office_switch_04
    title: Switches
    type: entities
  - entities:
    - entity: light.office_tablelight_02
      name: Tablelight 02
    - entity: sensor.office_tablelight_02_total_daily_energy
      name: Tablelight 02 Total Daily Energy
    - entity: sensor.office_tablelight_02_voltage
      name: Tablelight 02 Voltage
    - entity: sensor.office_tablelight_02_current
      name: Tablelight 02 Current
    - entity: sensor.office_tablelight_02_power
      name: Tablelight 02 Power
    - entity: sensor.office_tablelight_02_energy
      name: Tablelight 02 Energy
    - entity: light.office_tablelight_01
      name: Tablelight 01
    - entity: sensor.office_tablelight_01_total_daily_energy
      name: Tablelight 01 Total Daily Energy
    - entity: sensor.office_tablelight_01_voltage
      name: Tablelight 01 Voltage
    - entity: sensor.office_tablelight_01_current
      name: Tablelight 01 Current
    - entity: sensor.office_tablelight_01_power
      name: Tablelight 01 Power
    - entity: sensor.office_tablelight_01_energy
      name: Tablelight 01 Energy
    title: Lights
    type: entities
  path: office
  title: Office
- cards:
  - entities:
    - binary_sensor.office_switch_01
    - binary_sensor.office_switch_02
    - binary_sensor.office_switch_03
    - binary_sensor.office_switch_04
    - binary_sensor.stairwell_switch_01
    - binary_sensor.stairwell_switch_02
    - binary_sensor.stairwell_switch_03
    - binary_sensor.stairwell_switch_04
    title: Switches
    type: entities
  path: stairwell
  title: Stairwell
