---
action:
- service: light.toggle
  target:
    entity_id: light.kitchen_downlights_b
alias: Switch - Kitchen Downlights B
mode: single
trigger:
- entity_id: binary_sensor.kitchen_switch_01
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.kitchen_switch_03
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.kitchen_switch_04
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.kitchen_switch_01
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.kitchen_switch_03
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.kitchen_switch_04
  from: "off"
  platform: state
  to: "on"
