---
action:
- service: homeassistant.turn_off
  target:
    entity_id: light.kitchen_nightlights
alias: Kitchen Nightlights Off
condition:
- condition: and
  conditions:
  - condition: state
    entity_id:
    - light.kitchen_downlights_a
    state: "off"
  - condition: state
    entity_id:
    - light.kitchen_downlights_b
    state: "off"
  - condition: state
    entity_id:
    - sun.sun
    state: above_horizon
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - light.kitchen_downlights_a
  for:
    seconds: 15
  platform: state
  to: "off"
- entity_id:
  - light.kitchen_downlights_b
  for:
    seconds: 15
  platform: state
  to: "off"
- entity_id:
  - sun.sun
  platform: state
  to: above_horizon
