---
action:
- service: homeassistant.turn_on
  target:
    entity_id: switch.laundry_fan
alias: Laundry Fan On
condition:
- condition: or
  conditions:
  - condition: state
    entity_id:
    - light.laundry_downlights
    state: "on"
  - condition: state
    entity_id:
    - sensor.dryer_mode
    state: active
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - light.laundry_downlights
  platform: state
  to: "on"
- entity_id:
  - sensor.dryer_mode
  platform: state
  to: active
