---
action:
- service: homeassistant.turn_on
  target:
    entity_id: switch.laundry_fan
alias: Laundry Fan On
mode: single
trigger:
- entity_id:
  - light.laundry_downlights
  platform: state
  to: "on"
- above: 10
  entity_id:
  - sensor.laundry_dryer_power
  platform: numeric_state
