---
action:
- service: homeassistant.turn_off
  target:
    entity_id: switch.laundry_fan
alias: Laundry Fan Off
condition:
- condition: and
  conditions:
  - condition: state
    entity_id:
    - light.laundry_downlights
    state: "off"
  - condition: state
    entity_id:
    - sensor.dryer_mode
    state:
    - idle
    - unknown
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - light.laundry_downlights
  for:
    seconds: 15
  platform: state
  to: "off"
- entity_id:
  - sensor.dryer_mode
  platform: state
  to:
  - idle
  - unknown
