---
action:
- service: light.toggle
  target:
    entity_id: light.laundry_downlights
alias: Laundry Downlights
mode: single
trigger:
- entity_id: binary_sensor.laundry_switch_01
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.laundry_switch_02
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.laundry_switch_03
  from: "on"
  platform: state
  to: "off"
- entity_id: binary_sensor.laundry_switch_01
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.laundry_switch_02
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.laundry_switch_03
  from: "off"
  platform: state
  to: "on"
