---
action:
- service: homeassistant.turn_on
  target:
    entity_id: group.laundry_fan
alias: Laundry Fans On
mode: single
trigger:
- entity_id:
  - light.laundry_downlights
  platform: state
  to: "on"
- above: 10
  entity_id:
  - sensor.dryer_power
  platform: numeric_state
