---
action:
- service: homeassistant.turn_off
  target:
    entity_id: switch.ensuite_fan
alias: Ensuite Fan Off
mode: single
trigger:
- entity_id:
  - light.ensuite_downlights
  platform: state
  to: "off"
