---
action:
- service: homeassistant.turn_off
  target:
    entity_id: switch.bathroom_fan
alias: Bathroom Fan Off
mode: single
trigger:
- entity_id:
  - light.bathroom_downlights
  platform: state
  to: "off"
